@startuml
actor Joueur
participant ModeleJeu
participant Partie
participant ControleurPoseQuestion

Joueur -> ModeleJeu: poserQuestion(lieu, personnage, temps)
ModeleJeu -> Partie: poserQuestion(lieu, personnage, temps)
Partie -> ControleurPoseQuestion: poserQuestion(lieu, personnage, temps)
ControleurPoseQuestion -> VuePoseQuestion: poserQuestion(lieu, personnage, temps)
VuePoseQuestion -> ControleurPoseQuestion: validerQuestion(lieu, personnage, temps)
ControleurPoseQuestion -> Partie: validerQuestion(lieu, personnage, temps)
Partie -> ModeleJeu: validerQuestion(lieu, personnage, temps)
ModeleJeu -> Joueur: reponse

@enduml